#!/bin/bash
backupDate=$(ls $HOME | grep -E "^Backup-" | sort -n | tail -1 | cut -d "-" -f 2,3,4) 
backupDir=$HOME/"Backup-"$backupDate
restoreDir=$HOME/"restore"
if [[ ! -d $restoreDir ]]; then mkdir $restoreDir; fi

for i in $(ls $backupDir)
do
	if [ "$(echo $i | grep -Eo "[0-9]{4}-[0-9]{2}-[0-9]{2}")" == "" ]; then
		cp $backupDir/$i $restoreDir/$i
	fi
done
