#!/bin/bash
previous_ppid=-1
sum_running_time_avg=0
cnt_childrens=0

while read -r line ; do
	ppid=$(echo $line | awk -F: '{print $2}' | awk -F= '{print $2}')
	runavg=$(echo $line | awk -F: '{print $3}' | awk -F= '{print $2}')
	if (( previous_ppid != -1 && ppid != previous_ppid )) ; then
		echo "Average_Sleeping_Children_of_ParentID=$previous_ppid is $(echo "scale=2; $sum / $cnt" | bc -l)" >> ans5
		sum_running_time_avg=0
		cnt_childrens=0
	fi
	sum_running_time_avg=$(echo "scale=2; $sum_running_time_avg + $runavg" | bc -l)
	previous_ppid=$ppid
	((cnt++))
	echo $line >> ans5
done < test

echo Average_Sleeping_Children_of_ParentID=$previous_ppid is $(echo "scale=2; $sum / $cnt" | bc -l) >> ans5 
