#!/bin/bash
dateTime=$(date "+%F_%T")
mkdir ~/test && echo "catalog test was created successfully" > ~/report && touch ~/test/$dateTime
ping -c 1 https://www.net_nikogo.ru || echo "$dateTime An error has occured during ping net_nikogo.ru" >> ~/report
